name: flutter_super_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_js: ^0.8.3
  webview_flutter: 4.4.2
  archive: ^4.0.7
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  flutter_inappwebview: ^6.1.5
  shelf: ^1.4.1
  shelf_static: ^1.1.1
  shelf_router: ^1.1.3
  path: ^1.9.0
  mime: ^1.0.4
  dio: ^5.8.0+1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

